'use client';

import React from 'react';
import cx from 'classnames';
import type { Metadata } from 'next';
import Error from 'next/error';
import { Inter } from 'next/font/google';
import ErrorPage from 'src/components/ErrorPage';
import Footer from 'src/components/Footer';
import ThemeSwitcher from 'src/components/ThemeSwitcher';

import useSentryErrorReport from 'src/hooks/useSentryErrorReport';

import '../styles/base.scss';
import '../styles/global.css';

const inter = Inter({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-inter',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

interface GlobalErrorProps {
	error: Error & { digest?: string };
	reset: () => void;
}

const GlobalError: React.FC<GlobalErrorProps> = ({ error, reset }) => {
	useSentryErrorReport(error);

	return (
		<html lang='en' className='dark'>
			<body className={cx(inter.variable, 'body')}>
				<ThemeSwitcher />
				<ErrorPage
					title='Oops!'
					subTitle='Something went wrong'
					description='An unexpected error occured while loading this website'
					action={{
						onClick: () => reset(),
						label: 'Reload',
					}}
				/>
				<Footer />
			</body>
		</html>
	);
};

export default GlobalError;
