import React from 'react';
import cx from 'classnames';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from 'next-themes';
import Footer from 'src/components/Footer';
import ThemeSwitcher from 'src/components/ThemeSwitcher';

import { THEME_MODE_KEY } from 'src/data/contants';

import '../styles/base.scss';
import '../styles/global.css';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang='en'>
      <body className={cx(inter.variable, 'body')}>
        <ThemeProvider attribute='class' storageKey={THEME_MODE_KEY} enableSystem={false}>
          <ThemeSwitcher />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
