import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import cx from 'classnames';

const inter = Inter({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-inter',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className='dark'>
			<body
				className={cx(
					inter.variable,
					'bg-white dark:bg-black relative'
				)}>
				{children}
			</body>
		</html>
	);
}
