backend:
  name: git-gateway
  branch: main
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'
media_library:
  name: cloudinary
  config:
    cloud_name: ds8bd6wxr
    api_key: 785123966216323
collections:
  - label: 'Defaults'
    name: 'defaults'
    files:
      - label: 'Technologies'
        name: 'technologies'
        file: 'content/technologies/list.md'
        fields:
          - { label: 'Tech', name: 'tech', widget: 'list', required: true }
  - label: 'Home Page'
    name: 'home_page'
    files:
      - label: 'Header'
        name: 'header'
        file: 'content/home/header.md'
        fields:
          - { label: 'Name', name: 'name', widget: 'string', required: true }
          - { label: 'Role', name: 'role', widget: 'string', required: true }
          - { label: 'Summary', name: 'summary', widget: 'string', required: true }
      - label: 'About'
        name: 'about'
        file: 'content/home/about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string', required: true }
          - { label: 'Body', name: 'body', widget: 'markdown', required: true }
  - label: 'Experience'
    name: 'experience'
    folder: 'content/experience'
    create: true
    identifier_field: company
    fields:
      - { label: 'Company', name: 'company', widget: 'string', required: true }
      - { label: 'Website', name: 'url', widget: 'string', required: true }
      - { label: 'Industry', name: 'industry', widget: 'string', required: true }
      - { label: 'Location', name: 'location', widget: 'string', required: true }
      - { label: 'From', name: 'from', widget: 'string', required: true }
      - { label: 'To', name: 'to', widget: 'string', required: true }
      - label: 'Employment Type'
        name: 'employmentType'
        widget: 'select'
        required: true
        options:
          - { label: 'Full time', value: 'full-time' }
          - { label: 'Freelance', value: 'freelance' }
      - label: 'Technologies'
        name: 'technologies'
        widget: 'list'
        required: true
        allow_add: true
        default: []
        field:
          - label: 'Tech'
            name: 'tech'
            widget: 'relation'
            collection: 'defaults'
            file: 'technologies'
            value_field: 'technologies.*.tech'
            search_fields: ['technologies.*.tech']
            required: true
      - label: 'Related Articles'
        name: 'articles'
        widget: 'list'
        allow_add: true
        default: []
        fields:
          - label: 'Publication'
            name: 'publication'
            widget: 'string'
            required: true
          - label: 'URL'
            name: 'url'
            widget: 'string'
            required: true
      - label: 'Roles'
        name: 'roles'
        widget: 'list'
        allow_add: true
        default: []
        fields:
          - label: 'Role'
            name: 'role'
            widget: 'string'
            required: true
          - label: 'From'
            name: 'from'
            widget: 'string'
            required: true
          - label: 'To'
            name: 'to'
            widget: 'string'
            required: true
          - label: 'Body'
            name: 'body'
            widget: 'markdown'
            required: true
  - label: 'Projects'
    name: 'projects'
    folder: 'content/projects'
    create: true
    identifier_field: title
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Year', name: 'year', widget: 'string', required: true }
      - { label: 'Made at', name: 'made_at', widget: 'string' }
      - { label: 'Summary', name: 'summary', widget: 'string', required: true }
      - { label: 'Banner', name: 'thumbnail', widget: 'image', required: true }
      - label: 'Technologies'
        name: 'technologies'
        widget: 'list'
        required: true
        allow_add: true
        default: []
        field:
          - label: 'Tech'
            name: 'tech'
            widget: 'relation'
            collection: 'defaults'
            file: 'technologies'
            value_field: 'technologies.*.tech'
            search_fields: ['technologies.*.tech']
            required: true
      - label: 'Link'
        name: 'link'
        widget: 'object'
        fields:
          - { label: 'Label', name: 'label', widget: 'string' }
          - { label: 'URL', name: 'url', widget: 'string' }
      - label: 'Stats'
        name: 'stats'
        widget: 'list'
        allow_add: true
        default: []
        fields:
          - label: 'Count Text'
            name: 'count_text'
            widget: 'string'
            required: true
          - label: 'URL'
            name: 'url'
            widget: 'string'
            required: true
          - label: 'Type'
            name: 'type'
            widget: 'select'
            required: true
            options:
              - { label: 'Download', value: 'download' }
              - { label: 'Star', value: 'star' }
  - label: 'Articles'
    name: 'articles'
    folder: 'content/articles'
    create: true
    identifier_field: title
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Link', name: 'link', widget: 'string', equired: true }
      - { label: 'Date', name: 'date', widget: 'string', required: true }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image', required: true }
      - { label: 'Platform', name: 'platform', widget: 'string', required: true }
